/* original actions */
export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const MARK_TODO = 'MARK_TODO';
export const MARK_ALL = 'MARK_ALL';
export const CLEAR_MARKED = 'CLEAR_MARKED';

/* actions for async todos */
export const GET_TODOS_REQUEST = 'GET_TODOS_REQUEST';
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';
export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const EDIT_TODO_REQUEST = 'EDIT_TODO_REQUEST';
export const EDIT_TODO_SUCCESS = 'EDIT_TODO_SUCCESS';
export const MARK_TODO_REQUEST = 'MARK_TODO_REQUEST';
export const MARK_TODO_SUCCESS = 'MARK_TODO_SUCCESS';
export const MARK_ALL_REQUEST = 'MARK_ALL_REQUEST';
export const MARK_ALL_SUCCESS = 'MARK_ALL_SUCCESS';
export const CLEAR_MARKED_REQUEST = 'CLEAR_MARKED_REQUEST';
export const CLEAR_MARKED_SUCCESS = 'CLEAR_MARKED_SUCCESS';

